DROP DATABASE CRIME_DATA;
CREATE DATABASE IF NOT EXISTS CRIME_DATA;

CREATE TABLE IF NOT EXISTS BATONROUGECRIME_RAWDATA(
ID INT NOT NULL AUTO_INCREMENT,
FILENUMBER INT,
OFFENSEDATE DATE,
OFFENCETIME INTEGER,
CRIME VARCHAR(30),
OFFENSE VARCHAR(30),
OFFENCEDESCRIPTION VARCHAR(100),
FULLADDRESS VARCHAR(255),
ADDRESSNUMBER INTEGER,
STREETDIRECTION VARCHAR(20),
STREETNAME VARCHAR(255),
STREETTYPE VARCHAR(255),
CITY VARCHAR(255),
STATE VARCHAR(20) DEFAULT 'LA',
ZIPCODE INT ,
DISTRICT VARCHAR(10),
ZONE VARCHAR (10),
SUBZONE VARCHAR(10),
COMPLETEDISTRICT VARCHAR(15),
COUNCILDISTRICT VARCHAR(10),
CRIMEPREVENTIONDISTRICT VARCHAR(50),
GEOLOCATION VARCHAR(255),
PRIMARY KEY(ID)
);

LOAD DATA INFILE 'C:/Users/jha09/Downloads/DataAnalyticsBootcampAssignmentsAndChallenges/Challenge1/Legacy_Baton_Rouge_Crime_Incidents.csv'
INTO TABLE BATONROUGECRIME_RAWDATA
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '/n'
IGNORE 1 ROWS;

